name: lkongapp
description: A Flutter client for lkong.cn web forum.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.2.6+53

dependencies:
  flutter:
    sdk: flutter
  redux : ^3.0.0
  redux_logging: ^0.3.0
  flutter_redux : ^0.5.2
  built_value: ^6.1.4
  built_collection: ^4.0.0
  redux_thunk: ^0.2.1
  path_provider: 0.4.1
  http: ^0.12.0
  intl: any
  shared_preferences: 0.4.3
  synchronized: any
  uuid: any
  url_launcher: 4.1.0+1
  html_unescape: any
  flutter_sticky_header : ^0.3.4
  flutter_cupertino_settings: any
  material_search: ^0.2.8
  color: any
  fluttertoast: ^2.2.1
  photo_view: ^0.1.3
  image_picker: 0.4.12+1
  image_cropper: ^1.0.0
  connectivity: 0.3.2
  flutter_colorpicker: ^0.2.1
  package_info: any
  sensors: 0.3.5
  simple_permissions: ^0.1.9
  install_plugin: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  build: ^1.0.1
  build_runner: ^1.1.1
  built_value_generator: ^6.1.4
  source_gen: ^0.9.0+1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/noavatar.png
    - assets/image_placeholder.png
    - assets/blue.jpg
    - assets/black.jpg
    - assets/bq/em100.gif
    - assets/bq/em101.gif
    - assets/bq/em102.gif
    - assets/bq/em103.gif
    - assets/bq/em104.gif
    - assets/bq/em105.gif
    - assets/bq/em106.gif
    - assets/bq/em107.gif
    - assets/bq/em108.gif
    - assets/bq/em109.gif
    - assets/bq/em10.gif 
    - assets/bq/em110.gif
    - assets/bq/em111.gif
    - assets/bq/em112.gif
    - assets/bq/em113.gif
    - assets/bq/em114.gif
    - assets/bq/em115.gif
    - assets/bq/em11.gif 
    - assets/bq/em12.gif 
    - assets/bq/em13.gif 
    - assets/bq/em14.gif 
    - assets/bq/em15.gif 
    - assets/bq/em16.gif 
    - assets/bq/em17.gif 
    - assets/bq/em18.gif 
    - assets/bq/em19.gif 
    - assets/bq/em20.gif 
    - assets/bq/em218.gif
    - assets/bq/em219.gif
    - assets/bq/em21.gif 
    - assets/bq/em220.gif
    - assets/bq/em221.gif
    - assets/bq/em222.gif
    - assets/bq/em223.gif
    - assets/bq/em224.gif
    - assets/bq/em225.gif
    - assets/bq/em226.gif
    - assets/bq/em227.gif
    - assets/bq/em228.gif
    - assets/bq/em229.gif
    - assets/bq/em22.gif 
    - assets/bq/em230.gif
    - assets/bq/em231.gif
    - assets/bq/em232.gif
    - assets/bq/em233.gif
    - assets/bq/em234.gif
    - assets/bq/em235.gif
    - assets/bq/em236.gif
    - assets/bq/em237.gif
    - assets/bq/em238.gif
    - assets/bq/em239.gif
    - assets/bq/em23.gif 
    - assets/bq/em240.gif
    - assets/bq/em241.gif
    - assets/bq/em242.gif
    - assets/bq/em243.gif
    - assets/bq/em244.gif
    - assets/bq/em245.gif
    - assets/bq/em246.gif
    - assets/bq/em24.gif 
    - assets/bq/em250.gif
    - assets/bq/em251.gif
    - assets/bq/em252.gif
    - assets/bq/em253.gif
    - assets/bq/em254.gif
    - assets/bq/em255.gif
    - assets/bq/em256.gif
    - assets/bq/em257.gif
    - assets/bq/em258.gif
    - assets/bq/em259.gif
    - assets/bq/em25.gif 
    - assets/bq/em260.gif
    - assets/bq/em261.gif
    - assets/bq/em262.gif
    - assets/bq/em263.gif
    - assets/bq/em264.gif
    - assets/bq/em265.gif
    - assets/bq/em266.gif
    - assets/bq/em267.gif
    - assets/bq/em268.gif
    - assets/bq/em269.gif
    - assets/bq/em26.gif 
    - assets/bq/em270.gif
    - assets/bq/em271.gif
    - assets/bq/em272.gif
    - assets/bq/em273.gif
    - assets/bq/em274.gif
    - assets/bq/em275.gif
    - assets/bq/em276.gif
    - assets/bq/em277.gif
    - assets/bq/em278.gif
    - assets/bq/em279.gif
    - assets/bq/em27.gif 
    - assets/bq/em280.gif
    - assets/bq/em281.gif
    - assets/bq/em282.gif
    - assets/bq/em283.gif
    - assets/bq/em284.gif
    - assets/bq/em285.gif
    - assets/bq/em286.gif
    - assets/bq/em289.gif
    - assets/bq/em28.gif 
    - assets/bq/em290.gif
    - assets/bq/em291.gif
    - assets/bq/em292.gif
    - assets/bq/em293.gif
    - assets/bq/em294.gif
    - assets/bq/em295.gif
    - assets/bq/em296.gif
    - assets/bq/em297.gif
    - assets/bq/em298.gif
    - assets/bq/em299.gif
    - assets/bq/em29.gif 
    - assets/bq/em300.gif
    - assets/bq/em301.gif
    - assets/bq/em302.gif
    - assets/bq/em303.gif
    - assets/bq/em304.gif
    - assets/bq/em305.gif
    - assets/bq/em306.gif
    - assets/bq/em307.gif
    - assets/bq/em308.gif
    - assets/bq/em309.gif
    - assets/bq/em30.gif 
    - assets/bq/em310.gif
    - assets/bq/em31.gif 
    - assets/bq/em32.gif 
    - assets/bq/em33.gif 
    - assets/bq/em34.gif 
    - assets/bq/em35.gif 
    - assets/bq/em37.gif 
    - assets/bq/em38.gif 
    - assets/bq/em39.gif 
    - assets/bq/em400.gif
    - assets/bq/em401.gif
    - assets/bq/em402.gif
    - assets/bq/em403.gif
    - assets/bq/em404.gif
    - assets/bq/em405.gif
    - assets/bq/em406.gif
    - assets/bq/em407.gif
    - assets/bq/em408.gif
    - assets/bq/em409.gif
    - assets/bq/em40.gif 
    - assets/bq/em410.gif
    - assets/bq/em411.gif
    - assets/bq/em412.gif
    - assets/bq/em413.gif
    - assets/bq/em414.gif
    - assets/bq/em415.gif
    - assets/bq/em416.gif
    - assets/bq/em417.gif
    - assets/bq/em418.gif
    - assets/bq/em419.gif
    - assets/bq/em41.gif 
    - assets/bq/em420.gif
    - assets/bq/em421.gif
    - assets/bq/em422.gif
    - assets/bq/em423.gif
    - assets/bq/em424.gif
    - assets/bq/em425.gif
    - assets/bq/em426.gif
    - assets/bq/em427.gif
    - assets/bq/em428.gif
    - assets/bq/em429.gif
    - assets/bq/em42.gif 
    - assets/bq/em430.gif
    - assets/bq/em431.gif
    - assets/bq/em432.gif
    - assets/bq/em433.gif
    - assets/bq/em434.gif
    - assets/bq/em435.gif
    - assets/bq/em436.gif
    - assets/bq/em437.gif
    - assets/bq/em438.gif
    - assets/bq/em439.gif
    - assets/bq/em43.gif 
    - assets/bq/em440.gif
    - assets/bq/em441.gif
    - assets/bq/em442.gif
    - assets/bq/em443.gif
    - assets/bq/em444.gif
    - assets/bq/em445.gif
    - assets/bq/em446.gif
    - assets/bq/em447.gif
    - assets/bq/em448.gif
    - assets/bq/em449.gif
    - assets/bq/em44.gif 
    - assets/bq/em450.gif
    - assets/bq/em451.gif
    - assets/bq/em452.gif
    - assets/bq/em453.gif
    - assets/bq/em454.gif
    - assets/bq/em455.gif
    - assets/bq/em456.gif
    - assets/bq/em457.gif
    - assets/bq/em458.gif
    - assets/bq/em459.gif
    - assets/bq/em45.gif 
    - assets/bq/em460.gif
    - assets/bq/em461.gif
    - assets/bq/em462.gif
    - assets/bq/em463.gif
    - assets/bq/em464.gif
    - assets/bq/em465.gif
    - assets/bq/em46.gif 
    - assets/bq/em47.gif 
    - assets/bq/em48.gif 
    - assets/bq/em49.gif 
    - assets/bq/em50.gif 
    - assets/bq/em51.gif 
    - assets/bq/em52.gif 
    - assets/bq/em53.gif 
    - assets/bq/em54.gif 
    - assets/bq/em55.gif 
    - assets/bq/em56.gif 
    - assets/bq/em57.gif 
    - assets/bq/em58.gif 
    - assets/bq/em59.gif 
    - assets/bq/em60.gif 
    - assets/bq/em61.gif 
    - assets/bq/em62.gif 
    - assets/bq/em63.gif 
    - assets/bq/em64.gif 
    - assets/bq/em65.gif 
    - assets/bq/em66.gif 
    - assets/bq/em67.gif 
    - assets/bq/em68.gif 
    - assets/bq/em69.gif 
    - assets/bq/em70.gif 
    - assets/bq/em71.gif 
    - assets/bq/em72.gif 
    - assets/bq/em73.gif 
    - assets/bq/em74.gif 
    - assets/bq/em75.gif 
    - assets/bq/em76.gif 
    - assets/bq/em77.gif 
    - assets/bq/em78.gif 
    - assets/bq/em79.gif 
    - assets/bq/em80.gif 
    - assets/bq/em81.gif 
    - assets/bq/em82.gif 
    - assets/bq/em83.gif 
    - assets/bq/em84.gif 
    - assets/bq/em85.gif 
    - assets/bq/em86.gif 
    - assets/bq/em87.gif 
    - assets/bq/em88.gif 
    - assets/bq/em89.gif 
    - assets/bq/em90.gif 
    - assets/bq/em91.gif 
    - assets/bq/em92.gif 
    - assets/bq/em93.gif 
    - assets/bq/em94.gif 
    - assets/bq/em95.gif 
    - assets/bq/em96.gif 
    - assets/bq/em97.gif 
    - assets/bq/em98.gif 
    - assets/bq/em99.gif 
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
